version: '2.1'

volumes:
  esdata: {}

services:
  elasticsearch:
    environment:
      - xpack.security.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch